### PR TITLE
Topic/ara ucm

### PR DESCRIPTION
**Pull request by GordanM**

### CODE REVIEW

**Comment by tobsan** [comment]
The build reports misspelled/unknown words, please fix them.

**Comment by GordanM** [comment]
Fixed @tobsan .

**Review by tobsan — APPROVED** [review]

**Comment by tobsan** [comment]
@GordanM now you have merge conflicts again.

@thenor @rpannek @FlorentRevest will you review this or should we just merge it once the conflicts are fixed?

**Review by thenor — APPROVED** [review]
Looks good to me. Just note that there is a conflict in the aspell file.

**Review by FlorentRevest — APPROVED** [review]

**Review by rpannek — APPROVED** [review]

**Pull request merged**
