### PR TITLE
getting pelux: only one manifest name

### PR DESCRIPTION
**Pull request by tobsan**
After updating with one manifest only in the manifest repo, the SWF has
to be updated with matching instructions.

Signed-off-by: Tobias Olausson <tobias.olausson@pelagicore.com>

### CODE REVIEW

**Comment by GordanM** [comment]
Is there a similar chapter in the SWF that needs to be changed? Otherwise, looks great!

**Review by GordanM — APPROVED** [review]

**Comment by tobsan** [comment]
@GordanM this is the SWF...

**Comment by GordanM** [comment]
@ myself go home you're drunk. @tobsan sorry about that :). Carry on.

**Review by rpannek — COMMENTED** [review]
I assume those changes are made to align with how it is done right now, without the variants changes?

**Comment by tobsan** [comment]
@rpannek yes, that's correct.

**Review by rpannek — APPROVED** [review]

**Pull request merged**
