### PR TITLE
Bump blueprint

### PR DESCRIPTION
**Pull request by chuanjin**

### CODE REVIEW

**Comment by tobsan** [comment]
@chuanjin This fails due to spell-checking issues. Can you rebase on top of master once #105 is merged, please?

**Comment by chuanjin** [comment]
Yes, I notice that, will rebase it when it's ready.

**Comment by tobsan** [comment]
@chuanjin can you have a look if this is needed anymore? The PR that updated spelling also bumped the blueprint.

**Comment by chuanjin** [comment]
@tobsan 
Oh right, then probably it's not needed anymore. 
I think we should just close this PR.

**Pull request closed without merging**
