### PR TITLE
SDK: Link to the DLT documentation

### PR DESCRIPTION
**Pull request by FlorentRevest**
To be merged after https://github.com/Pelagicore/software-factory-blueprint/pull/114

### CODE REVIEW

**Review by frznlogic — APPROVED** [review]

**Review by GordanM — APPROVED** [review]

**Comment by GordanM** [comment]
@FlorentRevest there seem to be some issues with the references :)

**Comment by FlorentRevest** [comment]
@GordanM yes sure, because it depends on the blueprint PR that hasn't been merged yet ;) https://github.com/Pelagicore/software-factory-blueprint/pull/114

**Comment by GordanM** [comment]
@FlorentRevest isn't it though? :)

**Comment by FlorentRevest** [comment]
Err, I had to update the swf-blueprint submodule as well :)

**Pull request merged**
