### PR TITLE
conf.py.in: remove alpha tag from version

### PR DESCRIPTION
**Pull request by sashko**
Signed-off-by: Oleksandr Kravchuk <oleksandr.kravchuk@pelagicore.com>

### CODE REVIEW

**Review by rpannek — APPROVED** [review]

**Comment by martin-ejdestig** [comment]
v2.0 tag should be on this commit instead of current master?

**Comment by martin-ejdestig** [comment]
Could not find any documentation in repo for how releasing and tagging etc. is done, but it seems weird to have the v2.0 tag before this commit at least. Or?

Also, not sure who tagged since it is not annotated. So may not be you... anyway, just noticed it and thought I'd bring it up here since it seems related to me.

**Comment by sashko** [comment]
@martin-ejdestig  it went into v2.0 branch, so it's kinda obvious.

**Comment by TSAnsari** [comment]
@sashko seems you replied to the wrong guy :)

**Pull request merged**
